### ISSUE TITLE
Roghness and other such data lost after combining

### ISSUE THREAD

**Issue by nikhil-convrseai** [Grim-es/material-combiner-addon#115] opened 2024-10-11 12:32 UTC
Hi, 

I have been testing this addon for one of my project and have realised that post combining the materials it looses the data of roughness, specular , depth map and so on. How can I fix that?

**Comment by Grim-es** [comment] 2024-10-11 18:33
Hi, there is currently no estimated timeline for the implementation of multiple atlas types. At the moment, only a single atlas can be generated. For other types of textures, you'll need to manually create them using image editing software, with the generated atlas serving as a reference. The texture type per atlases feature was implemented in version [`2.0.3.3`](https://github.com/Grim-es/material-combiner-addon/releases/tag/2.0.3.3) which only works with Blender version up to and including 2.79.

Duplicate of #15.

**Closed by Grim-es** 2024-10-11 18:33 UTC
